foosball_elo/elo/urls.py
from django.urls import path
from . import views

app_name='elo_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('all/', views.AllView.as_view(), name='all'),
    path('<int:pk>/', views.PlayerDetailView.as_view(), name='player_detail'),
    path('game/submit_form/', views.SubmitGameView.as_view(), name='submit_form_game'),
    path('game/submit/', views.submit_game, name='submit_game'),
    path('updateratings', views.update_ratings, name='update_ratings')
]

foosball_elo/foosball_elo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from api.models import GameResource

game_resource = GameResource()

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("elo/", include('elo.urls'), name="elo"),
    path("", include('registration.urls'), name="registration"),
    path("api/", include(game_resource.urls))
]

foosball_elo/registration/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView

from . import views

app_name='registration'
urlpatterns = [
    path("", LoginView.as_view(template_name='registration/login.html', next_page=reverse_lazy('elo_app:index')), name="login"),
    path('player/submit_form/', views.SubmitPlayerView.as_view(), name='submit_form_player'), 
    path('player/submit/', views.submit_player, name='submit_player'),
]

foosball_elo/elo/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib import admin
from django.contrib.auth.models import User

from datetime import datetime

# Create your models here.
class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    player_name = models.CharField(max_length=50, unique=True)
    
    def get_rating(self, date: datetime.date = None) -> int:
        """ Returns player's rating at the time given by date, or latest rating if date isn't specified.
        """
        player_ratings = self.playerrating_set.all()
        
        if len(player_ratings) == 0:
            # Can only happen if player was added through admin interface.
            return 0
        if date == None:
            return player_ratings[len(player_ratings) - 1].rating
        if len(player_ratings) == 1:
            return player_ratings[0].rating
        elif date <= player_ratings[0].timestamp:
            # Can only happen in case game_date was at some point moved back in time
            # by a user with admin privileges.
            return player_ratings[0].rating
        elif date > player_ratings[len(player_ratings)-1].timestamp:
            return player_ratings[len(player_ratings)-1].rating
        
        # Bisection search for player's rating at the desired time.
        idx = 0
        while not (player_ratings[idx].timestamp < date and date <= player_ratings[idx+1].timestamp):
            if player_ratings[idx].timestamp >= date:
                idx = int(idx/2)
            elif date > player_ratings[idx+1].timestamp:
                idx += int((len(player_ratings) - 1 - idx) / 2)
            else:
                raise RuntimeError("This shouldn't happen!")
            
        return player_ratings[idx].rating   
    
    def __str__(self):
        return self.player_name
    
    class Meta:
        ordering = [models.functions.Upper('player_name')]    

    
class Game(models.Model):
    team_1_defense = models.ForeignKey(Player, on_delete=models.PROTECT, related_name='team_1_defense')
    team_1_attack = models.ForeignKey(Player, on_delete=models.PROTECT, related_name='team_1_attack')
    team_2_defense = models.ForeignKey(Player, on_delete=models.PROTECT, related_name='team_2_defense')
    team_2_attack = models.ForeignKey(Player, on_delete=models.PROTECT, related_name='team_2_attack')
    
    team_1_score = models.SmallIntegerField(validators=[MinValueValidator(0), 
                                                        MaxValueValidator(10)])
    team_2_score = models.SmallIntegerField(validators=[MinValueValidator(0),
                                                        MaxValueValidator(10)])
    
    date_played = models.DateField('date played')
    
    submitted_by = models.ForeignKey(User, on_delete=models.PROTECT)
    
    # Records whether the players in this game have had their rating updated based on its result
    updates_performed = models.BooleanField('player ratings updated?', default=False)
    
    def winner(self) -> int:
        if int(self.team_1_score) == 10 and int(self.team_2_score) < 10:
            return 1
        elif int(self.team_2_score) == 10 and int(self.team_1_score) < 10:
            return 2
        return 0
    
    def compute_rating_diffs(self, 
                             scaling_factor : int = 400, 
                             adaption_step : int = 64) -> tuple[int]:
        """ Computes the ratings diffs of both teams based on the outcome of the game.
            Returns a tuple containing rating diffs for team_1 and team_2 in that order.
            NB: How the rating diff is shared between the two players, should be determined
            by the caller of this method. 
        """
        team_1_rating = (self.team_1_defense.get_rating() + self.team_1_attack.get_rating()) * .5
        team_2_rating = (self.team_2_defense.get_rating() + self.team_2_attack.get_rating()) * .5
        
        team_1_expected_outcome = 1 / (1 + 10**((team_2_rating - team_1_rating) / scaling_factor))
        team_2_expected_outcome = 1 / (1 + 10**((team_1_rating - team_2_rating) / scaling_factor))
        winner = self.winner()
        if winner == 0:
            raise ValueError("Winner of game {} could not be determined.".format(self.id))
        team_1_diff = adaption_step * (int(winner==1) - team_1_expected_outcome)
        team_2_diff = adaption_step * (int(winner==2) - team_2_expected_outcome)
        return team_1_diff, team_2_diff
    
    def get_rating_diff_abs(self):
        return abs(self.compute_rating_diffs()[0])
    
    class Meta:
        # For ordering most recent to last
        ordering = ['-date_played']
        

class PlayerRating(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    timestamp = models.DateField('date')
    rating = models.IntegerField('elo rating')
    
    def get_player_name(self):
        return self.player.player_name
    
    class Meta:
        ordering = ['player_id', 'timestamp']

foosball_elo/elo/views.py
from django.db.models import Max
from django.db.models.query import QuerySet
from django.db.utils import IntegrityError
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, HttpResponseNotAllowed
from django.views import View, generic
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.contrib.auth.decorators import user_passes_test

from .models import Player, Game, PlayerRating

import decimal
from typing import Any
import datetime


#############
## HELPERS ##
#############

def is_valid_score(score1 : int, score2 : int) -> bool:
    return (score1 == 10 and score2 < 10) or (score2 == 10 and score1 < 10)

def are_valid_teams(team_1_defense : Player, 
                    team_1_attack : Player, 
                    team_2_defense : Player, 
                    team_2_attack : Player, 
                    invalid_team_member : list[str]):
    if team_1_defense.player_name == team_2_defense.player_name \
        or team_1_defense.player_name == team_2_attack.player_name:
        invalid_team_member.append(team_1_defense.player_name)
        return False
    elif team_1_attack.player_name == team_2_defense.player_name \
        or team_1_attack.player_name == team_2_attack.player_name:
        invalid_team_member.append(team_1_attack.player_name)
        return False
    return True
     
    
def compute_player_statistics(games : set[Game],
                              player: Player) -> tuple[int]:
    """ Returns (highest_opponent_rating, average_opponent_rating, games_won, games_lost, eggs_dealt_count, eggs_collected_count)
    """
    highest_opponent_rating = 0
    average_opponent_rating = 0
    games_won = 0
    games_lost = 0
    eggs_dealt_count = 0
    eggs_collected_count = 0
    
    for game in games:
        player_is_team_1 = player in [game.team_1_defense, game.team_1_attack]
        
        opponent_defense_rating = \
            (game.team_2_defense if player_is_team_1 else game.team_1_defense).get_rating(game.date_played)
            
        opponent_attack_rating = \
            (game.team_2_attack if player_is_team_1 else game.team_1_attack).get_rating(game.date_played)
            
        opponent_rating = .5 * (opponent_defense_rating + opponent_attack_rating)
        average_opponent_rating += opponent_rating
        highest_opponent_rating = max(highest_opponent_rating, opponent_rating)
        
        if game.winner() == 2-int(player_is_team_1):
            games_won += 1
        else:
            games_lost += 1
        
        eggs_dealt_count += int((game.team_2_score if player_is_team_1 else game.team_1_score) == 0)
        eggs_collected_count += int((game.team_1_score if player_is_team_1 else game.team_2_score) == 0)
    
    average_opponent_rating /= len(games) if len(games) > 0 else 1
    
    return highest_opponent_rating, average_opponent_rating, games_won, games_lost, eggs_dealt_count, eggs_collected_count

def get_player_statistics(player: Player) -> dict[str, int]:
    # Use sets to avoid one-player-teams (i.e., attack=defense) to
    # be counted twice. Get ready for some good old discrete measure theory
    # a.k.a. 'the pleasures of counting'.
    games_as_team_1_defense = set(Game.objects.filter(team_1_defense=player))
    games_as_team_1_attack = set(Game.objects.filter(team_1_attack=player))
    games_as_team_1 = games_as_team_1_defense.union(games_as_team_1_attack)

    defense_games_count = len(games_as_team_1_defense)
    attack_games_count = len(games_as_team_1_attack)   
    single_games_count = defense_games_count + attack_games_count - len(games_as_team_1)
    defense_games_count -= single_games_count
    attack_games_count -= single_games_count
    
    games_as_team_2_defense = set(Game.objects.filter(team_2_defense=player))
    games_as_team_2_attack = set(Game.objects.filter(team_2_attack=player))
    games_as_team_2 = games_as_team_2_defense.union(games_as_team_2_attack)
    
    defense_games_count += len(games_as_team_2_defense)
    attack_games_count += len(games_as_team_2_attack)
    single_games_team_2 = len(games_as_team_2_defense) + len(games_as_team_2_attack) - len(games_as_team_2)
    single_games_count += single_games_team_2
    defense_games_count -= single_games_team_2
    attack_games_count -= single_games_team_2
    
    highest_opponent_rating, average_opponent_rating, games_won, games_lost, eggs_dealt_count, eggs_collected_count \
    = compute_player_statistics(games_as_team_1.union(games_as_team_2),
                                player)
        
    out = {}
    out['game_count'] = defense_games_count + attack_games_count + single_games_count
    out['highest_opponent_rating'] = highest_opponent_rating
    out['average_opponent_rating'] = average_opponent_rating
    out['defense_games_count'] = defense_games_count
    out['attack_games_count'] = attack_games_count
    out['single_games_count'] = single_games_count
    out['games_won'] = games_won
    out['games_lost'] = games_lost
    out['eggs_dealt_count'] = eggs_dealt_count
    out['eggs_collected_count'] = eggs_collected_count
    
    return out
    

def get_all_rating_diffs(save_games: bool = False, penalize_inactivity: bool = False):
    all_players = sorted(Player.objects.all(), key=lambda a: -a.get_rating())
    diff_dict = dict(
        zip(list(Player.objects.all()), 
            [(None if penalize_inactivity else 0) for x in range(Player.objects.count())]
        )
    )
    
    unrecorded_games = Game.objects.filter(updates_performed=False)
    for game in unrecorded_games:
        team_1_diff, team_2_diff = game.compute_rating_diffs()
        
        for idx, player in enumerate([game.team_1_defense, 
                                      game.team_1_attack, 
                                      game.team_2_defense, 
                                      game.team_2_attack]):
            curr_diff = round(team_1_diff*.5) if idx < 2 else round(team_2_diff*.5)
            if diff_dict[player]:
                diff_dict[player] += curr_diff
            else:
                diff_dict[player] = curr_diff
            
        if save_games:
            game.updates_performed = True
            game.save()
    
    if not penalize_inactivity:
        return diff_dict
    
    for idx, player in enumerate(all_players):
        # If player has been inactive since last update, i.e., diff_dict[player] == None,
        # player loses 1 point for each active player ranking below them (but no more than 25 though),
        # and each such player gains 1 point, to keep the total number of points in the league unchanged.
        if not diff_dict[player]:
            penalty_diff = 0
            for other_idx in range(idx+1, len(all_players)):
                if penalty_diff <= -25:
                    break
                if diff_dict[all_players[other_idx]]:
                    diff_dict[all_players[other_idx]] += 1
                    penalty_diff -= 1
            diff_dict[player] = penalty_diff
            
    return diff_dict
           
    
class InvalidScoreError(Exception):
    def __init__(self, score1, score2):
        self.value = (score1, score2)
    
    def __str__(self):
        return "Indecisive scores: ({}, {}).".format(self.value[0], self.value[1])
                  
class InvalidTeamsError(Exception):
    def __init__(self, player_name : str):
        self.value = player_name
        
    def __str__(self):
        return "Invalid teams: {} plays on both teams".format(self.value)    
    
class InvalidDateEror(Exception):
    def __str__(self):
        return "Game cannot be in the future."


###########
## VIEWS ##
###########
class IndexView(generic.ListView):
    template_name = 'elo/index.html'
    context_object_name = 'top_5_list'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['recent_games'] = Game.objects.filter(updates_performed=False).order_by('-date_played')
        return context
    
    def get_queryset(self) -> QuerySet[Player]:
        players = sorted(Player.objects.all(), key=lambda a: -a.get_rating())[:5]
        rating_diffs = get_all_rating_diffs()
        return list(zip(players, [rating_diffs[p] for p in players]))
    
    
class AllView(generic.ListView):
    template_name = 'elo/player_list.html'
    context_object_name = 'player_list'
    
    
    
    def get_queryset(self) -> QuerySet[Player]:
        players = sorted(Player.objects.all(), key=lambda a: -a.get_rating())
        rating_diffs = get_all_rating_diffs()
        return list(zip(players, [rating_diffs[p] for p in players]))
    
class SubmitGameView(generic.ListView):
    template_name = 'elo/submit_game_form.html'
    context_object_name = 'all_players_list'
    
    def get_queryset(self):
        return Player.objects.all()
    
    
class PlayerDetailView(generic.DetailView):
    model = Player
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['high_score'] = self.object.playerrating_set.aggregate(Max('rating'))['rating__max']
        player_stats = get_player_statistics(self.object)
        for key in player_stats:
            ctx[key] = round(player_stats[key], 2)
        return ctx


@user_passes_test(lambda u:u.is_authenticated, login_url=reverse_lazy('registration:login'))
def submit_game(request: HttpRequest):
    if not request.method == 'POST':
        return render(request, 'elo/submit_game_form.html', {
            'all_players_list': Player.objects.order_by('player_name'),
            'error_message': 'Something went wrong. Please try again'
        })
    data = request.POST
    try:
        team_1_defense = Player.objects.get(pk=data['winning_team_defense'])
        team_1_attack = Player.objects.get(pk=data['winning_team_attack'])

foosball_elo/elo/templates/elo/index.html
<!doctype html>

<html lang="en-US">
    <head>
        <meta charset='utf-8'>
        <title>Elo</title>
    </head>
    <body>
        <h1>Overview</h1>
        <div>
            {% if top_5_list %}
            <h2>Top 5:</h2>
                <table border=1>
                    <thead>
                        <tr>
                            <th>Position</th>
                            <th>Player</th>
                            <th>Rating</th>
                            <th>Pending rating update</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for player in top_5_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'elo_app:player_detail' player.0.id %}"> {{ player.0.player_name }}</a></td>
                            <td>{{ player.0.get_rating }}</td>
                            <td>{{ player.1 }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No top 5 available!</p>
            {% endif %}
        </div>
        <div>
            <h2>Pending games*</h2>
            <table border=1>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Winning team</th>
                        <th>Losing team</th>
                        <th>Score</th>
                        <th>Submitted by</th>
                    </tr>
                </thead>
                <tbody>
                    {% for game in recent_games %}
                    <tr>
                        <td>
                            {{ game.date_played }}
                        </td>
                        <td>{{ game.team_1_defense }}, {{ game.team_1_attack }}</td>
                        <td>{{ game.team_2_defense}}, {{ game.team_2_attack }}</td>
                        <td>{{ game.team_1_score }} - {{ game.team_2_score }}</td>
                        <td>{{ game.submitted_by }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p>
                * The games displayed here are the ones that have been recorded but have not yet been used 
                to compute new ratings for the players involved. Ratings are updated once every week.
            </p>
        </div>
        <form action="{% url 'elo_app:update_ratings' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Update ratings">
        </form>
       
        <br>
        <a href={% url 'elo_app:all' %}>All players</a>
        <br>
        <a href={% url 'elo_app:submit_form_game' %}>Submit a game</a>
        <br>
        <a href={% url 'registration:login' %}>Home</a>
    </body>
</html>

foosball_elo/elo/templates/elo/player_list.html
<!doctype html>

<html lang="en-US">
    <head>
        <meta charset='utf-8'>
        <title>All players</title>
    </head>
    <body>
        <h1>All players</h1>
        {% if player_list %}
        <h2>Ranking:</h2>
            <table border=1>
                <thead>
                    <tr>
                        <th>Position</th>
                        <th>Player</th>
                        <th>Rating</th>
                        <th>Pending rating update</th>
                    </tr>
                </thead>
                <tbody>
                    {% for player in player_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'elo_app:player_detail' player.0.id %}"> {{ player.0.player_name }}</a></td>
                        <td>{{ player.0.get_rating }}</td>
                        <td>{{ player.1 }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No players available!</p>
        {% endif %}
        <a href={% url 'elo_app:index' %}>Back to overview</a>
    </body>
</html>

foosball_elo/elo/templates/elo/submit_form.html
<!doctype html>

<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <title>Submit form</title>
    </head>
    <body>
        <div>
            <form action="{% url 'elo_app:submit_game' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend><h1>Submit a game</h1></legend>
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    <div name="team1">
                        <strong>Team 1</strong><br>
                        <label for="team_1_defense">Team 1 defense</label>
                        <select id="team_1_defense" name="team_1_defense">
                            <option disabled selected value> -- select a player -- </option>
                            {% for player in all_players_list %}
                                <option value={{ player.id }}>{{ player.player_name }}</option>
                            {% endfor %}
                        </select><br>
                        <label for="team_1_attack">Team 1 attack</label>
                        <select id="team_1_attack" name="team_1_attack">
                            <option disabled selected value> -- select a player -- </option>
                            {% for player in all_players_list %}
                                <option value={{ player.id }}>{{ player.player_name }}</option>
                            {% endfor %}
                        </select><br>
                    </div>
                    <div name="team2">
                        <strong>Team 2</strong><br>
                        <label for="team_2_defense">Team 2 defense</label>
                        <select id="team_2_defense" name="team_2_defense">
                            <option disabled selected value> -- select a player -- </option>
                            {% for player in all_players_list %}
                                <option value={{ player.id }}>{{ player.player_name }}</option>
                            {% endfor %}
                        </select><br>
                        <label for="team_2_attack">Team 2 attack</label>
                        <select id="team_2_attack" name="team_2_attack">
                            <option disabled selected value> -- select a player -- </option>
                            {% for player in all_players_list %}
                                <option value={{ player.id }}>{{ player.player_name }}</option>
                            {% endfor %}
                        </select><br>
                    </div>
                    <div name="score">
                        <label for="team_1_score">Team 1 score</label>
                        <select id="team_1_score" name="team_1_score">
                            <option value=0 selected>0</option>
                            {% for i in '0123456789'|make_list %}
                                <option value={{ forloop.counter }}>{{ forloop.counter }}</option>
                            {% endfor %}
                        </select>
                        <label for="team_2_score">Team 2 score</label>
                        <select id="team_2_score" name="team_2_score">
                            <option value=0 selected>0</option>
                            {% for i in '0123456789'|make_list %}
                                <option value={{ forloop.counter }}>{{ forloop.counter }}</option>
                            {% endfor %}
                        </select><br>
                    </div>
                    <div name="date">
                        <label for="date">Date of game</label>
                        <input type="date" name="date" id="date">
                    </div>
                </fieldset>
                <input type="submit" value="Submit">
            </form>
        </div>
        <br>
        <a href={% url 'elo_app:index'%}>Back to home page</a>
    </body>

</html>

foosball_elo/elo/templates/elo/submit_game_form.html
<!doctype html>

<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <title>Submit game form</title>
    </head>
    <body>
        <div>
            <form action="{% url 'elo_app:submit_game' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend><h1>Submit a game</h1></legend>
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    <div name="winners">
                        <strong>Winning team</strong><br>
                        <label for="winning_team_defense">Winning team defense: </label>
                        <select id="winning_team_defense" name="winning_team_defense" required>
                            <option disabled selected value> -- select a player -- </option>
                            {% for player in all_players_list %}
                                <option value={{ player.id }}>{{ player.player_name }}</option>
                            {% endfor %}
                        </select><br>
                        <label for="winning_team_attack">Winning team attack: </label>
                        <select id="winning_team_attack" name="winning_team_attack" required>
                            <option disabled selected value> -- select a player -- </option>
                            {% for player in all_players_list %}
                                <option value={{ player.id }}>{{ player.player_name }}</option>
                            {% endfor %}
                        </select><br>
                    </div>
                    <div name="losers">
                        <strong>Losing team</strong><br>
                        <label for="losing_team_defense">Losing team defense: </label>
                        <select id="losing_team_defense" name="losing_team_defense" required>
                            <option disabled selected value> -- select a player -- </option>
                            {% for player in all_players_list %}
                                <option value={{ player.id }}>{{ player.player_name }}</option>
                            {% endfor %}
                        </select><br>
                        <label for="losing_team_attack">Losing team attack: </label>
                        <select id="losin_team_attack" name="losing_team_attack" required>
                            <option disabled selected value> -- select a player -- </option>
                            {% for player in all_players_list %}
                                <option value={{ player.id }}>{{ player.player_name }}</option>
                            {% endfor %}
                        </select><br>
                    </div>
                    <div name="score">
                        <strong>Result</strong><br>
                        <label for="losing_team_score">Losing team score: </label>
                        <select id="losing_team_score" name="losing_team_score" required>
                            <option value=0 selected>0</option>
                            {% for i in '0123456789'|make_list %}
                                <option value={{ forloop.counter }}>{{ forloop.counter }}</option>
                            {% endfor %}
                        </select>
                        {% comment %} <label for="team_2_score">Team 2 score: </label>
                        <select id="team_2_score" name="team_2_score" required>
                            <option value=0 selected>0</option>
                            {% for i in '0123456789'|make_list %}
                                <option value={{ forloop.counter }}>{{ forloop.counter }}</option>
                            {% endfor %}
                        </select><br> {% endcomment %}
                    </div>
                    <div name="date">
                        <label for="date">Date of game: </label>
                        <input type="date" name="date" id="date" required>
                    </div>
                </fieldset>
                <input type="submit" value="Submit">
            </form>
        </div>
        <br>
        <a href={% url 'elo_app:index'%}>Back to overview</a>
    </body>

</html>